# Generated by Django 4.2.16 on 2024-11-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0003_reservation_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
    ]
