# Generated by Django 4.2.16 on 2024-11-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0004_remove_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
