# Generated by Django 4.2.16 on 2024-11-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0008_alter_passenger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
    ]
